# Generated by Django 3.1.4 on 2020-12-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_course',
            name='video_link',
            field=models.TextField(),
        ),
    ]
