# Generated by Django 3.1.4 on 2020-12-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20201227_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_course',
            name='quote',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
