# Generated by Django 3.1.4 on 2020-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_auto_20201227_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='htmlphoto/')),
                ('video_link', models.TextField()),
                ('course_detail', models.TextField()),
                ('quote', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CssCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='htmlphoto/')),
                ('video_link', models.TextField()),
                ('course_detail', models.TextField()),
                ('quote', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
