# Generated by Django 3.1.4 on 2020-12-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_bootstrapcourse_csscourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csscourse',
            name='video_link',
            field=models.CharField(max_length=200),
        ),
    ]
