# Generated by Django 3.1.4 on 2020-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoCourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangocourse',
            name='video_link',
            field=models.CharField(max_length=200),
        ),
    ]
