# Generated by Django 3.1.4 on 2020-12-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=225),
        ),
    ]
