# Generated by Django 3.1.4 on 2020-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('instagrm', models.CharField(blank=True, max_length=200)),
                ('twetter', models.CharField(blank=True, max_length=200)),
                ('gplus', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='userprofile/')),
            ],
        ),
    ]
